[project]
name = "Emailzen"
version = "1.0.0"
description = "A minimalist, open-source, AI built email client"
requires-python = ">=3.10"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "flet",
    "google-auth>=2.20.0",
    "google-auth-oauthlib>=1.0.0",
    "google-api-python-client>=2.100.0",
    "keyring>=23.0.0",
    "httpx>=0.24.0",
]

[dependency-groups]
dev = [
    "flet-cli",
    "flet-desktop",
    "flet-web"
]

[tool.flet.metadata]
title = "Counter"

[tool.flet.gallery]
categories = ["Getting Started"]

[tool.flet]
org = "dev.flet"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"
