name: Build and Release Emailzen

on:
  push:
    tags:
      - 'v*' # Se déclenche à chaque tag de version (ex: v1.0.0)
  workflow_dispatch: # Permet aussi de le lancer manuellement si besoin

env:
  UV_PYTHON: '3.11' # Version de Python cible pour uv
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1 # Évite les animations de texte cassées en CI/CD
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Supprime l'avertissement de dépréciation de Node.js 20

jobs:
  release:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Évite qu'un échec sur un OS n'annule instantanément l'autre
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            output_path: build/linux
            asset_name: emailzen-linux.tar.gz
            needs_linux_deps: true
          - os: windows-latest
            platform: windows
            output_path: build/windows
            asset_name: emailzen-windows.zip
            needs_linux_deps: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-up@v6

      - name: Install Linux Dependencies
        if: matrix.needs_linux_deps
        shell: bash
        run: |
          sudo apt update --allow-releaseinfo-change
          sudo apt-get install -y --no-install-recommends \
            clang ninja-build libgtk-3-dev libasound2-dev libmpv-dev mpv \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 \
            pkg-config libsecret-1-0 libsecret-1-dev
          sudo apt-get clean

      # Note: Le SDK Flutter est géré et téléchargé à la bonne version automatiquement par Flet grâce au flag --yes
      - name: Flet Build App
        shell: bash
        run: |
          uv run flet build ${{ matrix.platform }} --yes --verbose

      - name: Archive Linux Build
        if: matrix.platform == 'linux'
        shell: bash
        run: |
          tar -czf ${{ matrix.asset_name }} -C ${{ matrix.output_path }} .

      - name: Archive Windows Build
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          Compress-Archive -Path "${{ matrix.output_path }}\*" -DestinationPath "${{ matrix.asset_name }}"

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}